# Generated by Django 3.1.1 on 2020-09-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100)),
                ('price_plan_id', models.CharField(blank=True, max_length=255)),
                ('days_valid', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('banner_message', models.CharField(blank=True, max_length=255)),
                ('is_displayed_on_site', models.BooleanField(default=True, verbose_name='Is displayed for purchase')),
                ('is_subscription', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('initiation_date', models.DateField(blank=True)),
                ('expiration_date', models.DateField(blank=True)),
                ('payment_status', models.CharField(max_length=100)),
                ('membership_config', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='membership.membershipconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AuxMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('test2', models.CharField(max_length=100)),
                ('test12', models.CharField(max_length=100)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aux_membership', to='membership.membership')),
            ],
        ),
    ]
