# Generated by Django 3.1.1 on 2020-09-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxmembership',
            name='test12',
        ),
        migrations.RemoveField(
            model_name='auxmembership',
            name='test2',
        ),
        migrations.AlterField(
            model_name='auxmembership',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aux_members', to='membership.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='initiation_date',
            field=models.DateField(),
        ),
    ]
