# Generated by Django 3.0.7 on 2020-09-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200607_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_config_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('initiation_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100)),
                ('price_plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('days_valid', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, null=True)),
                ('banner_message', models.CharField(max_length=255)),
                ('is_displayed_on_site', models.BooleanField(default=True, verbose_name='Is displayed for purchase')),
                ('is_subscription', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=1)),
            ],
        ),
    ]
