# Generated by Django 3.1.1 on 2020-09-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auxmembership_membership_membershipconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
