# Generated by Django 3.1.1 on 2020-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_delete_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipconfig',
            name='banner_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
